=== ruslanjan/Protium/Protium/src/main/resources/schemas/module.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Protium Module",
	"type": "object",
	"description": "Schema of Protium module's 'module.json' manifest file.",
	"properties": {
		"mainClass": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"version": {
			"type": "string"
		},
		"author": {
			"type": "string"
		},
		"description": {
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string"
			}
		}
	},
	"required": [ "id", "mainClass" ]
}

=== ruslanjan/Protium/PTE/src/main/resources/module.json
{
	"id": "LibPTE/Basic",
	"mainClass": "net.protium.modules.pte.Responder",
	"name": "PTE library",
	"description": [
		"LibPTE is Protium template engine based on FreeMarker template engine.",
		"LibPTE is a public library, not callable module. So it hasn't any route actions!",
		"",
		"Note: LibPTE is written in Groovy"
	],
	"author": "Protium Team"
}

=== ruslanjan/Protium/PAuthFrontend/src/main/resources/module.json
{
	"id": "PAuthFrontend-AM",
	"name": "PAuthFrontend AM Edition - Part of PAuth",
	"version": "v0.0.1/dev",
	"author": "Protium Team - Ussoltsev",
	"description": [
		"PAuth",
		"Default auth system from Protium developers.",
		"=========",
		"PAuth Frontend AM Edition works on Angular Material web-framework."
	],
	"mainClass": "net.protium.modules.pauth.frontend.core.PAuthFrontend"
}
